import type { Contact, Product } from '../types'

export const PRODUCTS_DATA: Product[] = [
	{
		id: 'prod1',
		name: 'Eco-Friendly Water Bottle',
		description:
			'Stay hydrated with this stylish and reusable water bottle. Made from BPA-free materials.',
		price: 24.99,
		category: 'Accessories',
		imageUrl: 'https://picsum.photos/seed/prod1/400/300',
		stock: 150,
		rating: 4.5,
	},
	{
		id: 'prod2',
		name: 'Wireless Noise-Cancelling Headphones',
		description:
			'Immerse yourself in sound with these premium over-ear headphones. Long battery life.',
		price: 199.5,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod2/400/300',
		stock: 75,
		rating: 4.8,
	},
	{
		id: 'prod3',
		name: 'Organic Cotton T-Shirt',
		description:
			'Comfortable and sustainable, this t-shirt is a wardrobe staple.',
		price: 35.0,
		category: 'Apparel',
		imageUrl: 'https://picsum.photos/seed/prod3/400/300',
		stock: 200,
		rating: 4.2,
	},
	{
		id: 'prod4',
		name: 'Smart Fitness Tracker',
		description:
			'Monitor your activity, sleep, and heart rate with this sleek fitness tracker.',
		price: 89.99,
		category: 'Wearables',
		imageUrl: 'https://picsum.photos/seed/prod4/400/300',
		stock: 120,
		rating: 4.6,
	},
	{
		id: 'prod5',
		name: 'Artisan Coffee Beans',
		description:
			'Freshly roasted, single-origin coffee beans for the perfect brew.',
		price: 18.75,
		category: 'Groceries',
		imageUrl: 'https://picsum.photos/seed/prod5/400/300',
		stock: 300,
		rating: 4.9,
	},
	{
		id: 'prod6',
		name: 'Ultra-Slim Laptop Stand',
		description:
			'Ergonomic aluminum laptop stand that improves posture and reduces neck strain.',
		price: 89.99,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod6/400/300',
		stock: 85,
		rating: 4.4,
	},
	{
		id: 'prod7',
		name: 'Bamboo Phone Case',
		description:
			'Sustainable and stylish phone case made from eco-friendly bamboo.',
		price: 29.99,
		category: 'Accessories',
		imageUrl: 'https://picsum.photos/seed/prod7/400/300',
		stock: 180,
		rating: 4.3,
	},
	{
		id: 'prod8',
		name: 'Premium Yoga Mat',
		description:
			'Non-slip yoga mat with excellent cushioning for all types of exercises.',
		price: 65.00,
		category: 'Sports',
		imageUrl: 'https://picsum.photos/seed/prod8/400/300',
		stock: 95,
		rating: 4.7,
	},
	{
		id: 'prod9',
		name: 'Wireless Charging Pad',
		description:
			'Fast wireless charging pad compatible with all Qi-enabled devices.',
		price: 39.99,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod9/400/300',
		stock: 140,
		rating: 4.5,
	},
	{
		id: 'prod10',
		name: 'Gourmet Chocolate Box',
		description:
			'Handcrafted assorted chocolates made with premium Belgian cocoa.',
		price: 42.50,
		category: 'Groceries',
		imageUrl: 'https://picsum.photos/seed/prod10/400/300',
		stock: 60,
		rating: 4.8,
	},
	{
		id: 'prod11',
		name: 'Ceramic Coffee Mug Set',
		description:
			'Set of 4 handmade ceramic mugs perfect for your morning coffee ritual.',
		price: 55.00,
		category: 'Home & Kitchen',
		imageUrl: 'https://picsum.photos/seed/prod11/400/300',
		stock: 110,
		rating: 4.6,
	},
	{
		id: 'prod12',
		name: 'LED Desk Lamp',
		description:
			'Adjustable LED desk lamp with multiple brightness levels and color temperatures.',
		price: 79.99,
		category: 'Home & Kitchen',
		imageUrl: 'https://picsum.photos/seed/prod12/400/300',
		stock: 75,
		rating: 4.4,
	},
	{
		id: 'prod13',
		name: 'Merino Wool Scarf',
		description:
			'Luxurious and warm merino wool scarf available in multiple colors.',
		price: 68.00,
		category: 'Apparel',
		imageUrl: 'https://picsum.photos/seed/prod13/400/300',
		stock: 45,
		rating: 4.7,
	},
	{
		id: 'prod14',
		name: 'Portable Bluetooth Speaker',
		description:
			'Compact waterproof speaker with 12-hour battery life and crystal clear sound.',
		price: 125.99,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod14/400/300',
		stock: 90,
		rating: 4.6,
	},
	{
		id: 'prod15',
		name: 'Essential Oils Gift Set',
		description:
			'Collection of 6 pure essential oils for aromatherapy and relaxation.',
		price: 89.95,
		category: 'Health & Beauty',
		imageUrl: 'https://picsum.photos/seed/prod15/400/300',
		stock: 65,
		rating: 4.8,
	},
]

export const CONTACTS_DATA: Contact[] = [
	{
		id: 'cont1',
		firstName: 'Alice',
		lastName: 'Smith',
		email: 'alice.smith@example.com',
		phone: '555-0101',
		address: {
			street: '123 Oak St',
			city: 'Springfield',
			zipCode: '62704',
			country: 'USA',
		},
		company: 'Innovatech Ltd.',
		avatarUrl: 'https://picsum.photos/seed/cont1/100/100',
	},
	{
		id: 'cont2',
		firstName: 'Bob',
		lastName: 'Johnson',
		email: 'bob.johnson@example.com',
		phone: '555-0102',
		address: {
			street: '456 Pine Ave',
			city: 'Rivertown',
			zipCode: '90210',
			country: 'USA',
		},
		company: 'Solutions Inc.',
		avatarUrl: 'https://picsum.photos/seed/cont2/100/100',
	},
	{
		id: 'cont3',
		firstName: 'Carol',
		lastName: 'Williams',
		email: 'carol.williams@example.com',
		phone: '555-0103',
		address: {
			street: '789 Maple Dr',
			city: 'Brookside',
			zipCode: '30303',
			country: 'USA',
		},
		company: 'TechCorp',
		avatarUrl: 'https://picsum.photos/seed/cont3/100/100',
	},
	{
		id: 'cont4',
		firstName: 'David',
		lastName: 'Brown',
		email: 'david.brown@example.com',
		phone: '555-0104',
		address: {
			street: '101 Birch Ln',
			city: 'Hillvalley',
			zipCode: '10001',
			country: 'USA',
		},
		company: 'Future Systems',
		avatarUrl: 'https://picsum.photos/seed/cont4/100/100',
	},
	{
		id: 'cont5',
		firstName: 'Eve',
		lastName: 'Davis',
		email: 'eve.davis@example.com',
		phone: '555-0105',
		address: {
			street: '202 Cedar Rd',
			city: 'Lakewood',
			zipCode: '80202',
			country: 'USA',
		},
		company: 'WebWorks',
		avatarUrl: 'https://picsum.photos/seed/cont5/100/100',
	},
	{
		id: 'cont6',
		firstName: 'Frank',
		lastName: 'Miller',
		email: 'frank.miller@example.com',
		phone: '555-0106',
		address: {
			street: '303 Elm St',
			city: 'Greenfield',
			zipCode: '54321',
			country: 'USA',
		},
		company: 'DataFlow Analytics',
		avatarUrl: 'https://picsum.photos/seed/cont6/100/100',
	},
	{
		id: 'cont7',
		firstName: 'Grace',
		lastName: 'Wilson',
		email: 'grace.wilson@example.com',
		phone: '555-0107',
		address: {
			street: '404 Willow Way',
			city: 'Northbridge',
			zipCode: '67890',
			country: 'USA',
		},
		company: 'Creative Solutions',
		avatarUrl: 'https://picsum.photos/seed/cont7/100/100',
	},
	{
		id: 'cont8',
		firstName: 'Henry',
		lastName: 'Taylor',
		email: 'henry.taylor@example.com',
		phone: '555-0108',
		address: {
			street: '505 Aspen Ave',
			city: 'Westfield',
			zipCode: '12345',
			country: 'USA',
		},
		company: 'Global Enterprises',
		avatarUrl: 'https://picsum.photos/seed/cont8/100/100',
	},
	{
		id: 'cont9',
		firstName: 'Isabella',
		lastName: 'Anderson',
		email: 'isabella.anderson@example.com',
		phone: '555-0109',
		address: {
			street: '606 Poplar St',
			city: 'Eastville',
			zipCode: '98765',
			country: 'USA',
		},
		company: 'Innovation Labs',
		avatarUrl: 'https://picsum.photos/seed/cont9/100/100',
	},
	{
		id: 'cont10',
		firstName: 'Jack',
		lastName: 'Thomas',
		email: 'jack.thomas@example.com',
		phone: '555-0110',
		address: {
			street: '707 Spruce Dr',
			city: 'Southport',
			zipCode: '24680',
			country: 'USA',
		},
		company: 'TechVision Inc.',
		avatarUrl: 'https://picsum.photos/seed/cont10/100/100',
	},
	{
		id: 'cont11',
		firstName: 'Katherine',
		lastName: 'Jackson',
		email: 'katherine.jackson@example.com',
		phone: '555-0111',
		address: {
			street: '808 Magnolia Blvd',
			city: 'Central City',
			zipCode: '13579',
			country: 'USA',
		},
		company: 'Digital Dynamics',
		avatarUrl: 'https://picsum.photos/seed/cont11/100/100',
	},
	{
		id: 'cont12',
		firstName: 'Liam',
		lastName: 'White',
		email: 'liam.white@example.com',
		phone: '555-0112',
		address: {
			street: '909 Sycamore St',
			city: 'Harbor View',
			zipCode: '86420',
			country: 'USA',
		},
		company: 'NextGen Solutions',
		avatarUrl: 'https://picsum.photos/seed/cont12/100/100',
	},
	{
		id: 'cont13',
		firstName: 'Maya',
		lastName: 'Harris',
		email: 'maya.harris@example.com',
		phone: '555-0113',
		address: {
			street: '1010 Cherry Ln',
			city: 'Mountain View',
			zipCode: '97531',
			country: 'USA',
		},
		company: 'Cloud Computing Corp',
		avatarUrl: 'https://picsum.photos/seed/cont13/100/100',
	},
	{
		id: 'cont14',
		firstName: 'Nathan',
		lastName: 'Martin',
		email: 'nathan.martin@example.com',
		phone: '555-0114',
		address: {
			street: '1111 Redwood Ave',
			city: 'Valley Springs',
			zipCode: '11223',
			country: 'USA',
		},
		company: 'Smart Systems Ltd.',
		avatarUrl: 'https://picsum.photos/seed/cont14/100/100',
	},
	{
		id: 'cont15',
		firstName: 'Olivia',
		lastName: 'Garcia',
		email: 'olivia.garcia@example.com',
		phone: '555-0115',
		address: {
			street: '1212 Dogwood Dr',
			city: 'Riverside',
			zipCode: '44556',
			country: 'USA',
		},
		company: 'Future Tech Innovations',
		avatarUrl: 'https://picsum.photos/seed/cont15/100/100',
	},
]
