import type { Contact, Product } from '../types'

export const PRODUCTS_DATA: Product[] = [
	{
		id: 'prod1',
		name: 'Eco-Friendly Water Bottle',
		description:
			'Stay hydrated with this stylish and reusable water bottle. Made from BPA-free materials.',
		price: 24.99,
		category: 'Accessories',
		imageUrl: 'https://picsum.photos/seed/prod1/400/300',
	},
	{
		id: 'prod2',
		name: 'Wireless Noise-Cancelling Headphones',
		description:
			'Immerse yourself in sound with these premium over-ear headphones. Long battery life.',
		price: 199.5,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod2/400/300',
	},
	{
		id: 'prod3',
		name: 'Organic Cotton T-Shirt',
		description:
			'Comfortable and sustainable, this t-shirt is a wardrobe staple.',
		price: 35.0,
		category: 'Apparel',
		imageUrl: 'https://picsum.photos/seed/prod3/400/300',
	},
	{
		id: 'prod4',
		name: 'Smart Fitness Tracker',
		description:
			'Monitor your activity, sleep, and heart rate with this sleek fitness tracker.',
		price: 89.99,
		category: 'Wearables',
		imageUrl: 'https://picsum.photos/seed/prod4/400/300',
	},
	{
		id: 'prod5',
		name: 'Artisan Coffee Beans',
		description:
			'Freshly roasted, single-origin coffee beans for the perfect brew.',
		price: 18.75,
		category: 'Groceries',
		imageUrl: 'https://picsum.photos/seed/prod5/400/300',
	},
	{
		id: 'prod6',
		name: 'Ultra-Slim Laptop Stand',
		description:
			'Ergonomic aluminum laptop stand that improves posture and reduces neck strain.',
		price: 89.99,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod6/400/300',
	},
	{
		id: 'prod7',
		name: 'Bamboo Phone Case',
		description:
			'Sustainable and stylish phone case made from eco-friendly bamboo.',
		price: 29.99,
		category: 'Accessories',
		imageUrl: 'https://picsum.photos/seed/prod7/400/300',
	},
	{
		id: 'prod8',
		name: 'Premium Yoga Mat',
		description:
			'Non-slip yoga mat with excellent cushioning for all types of exercises.',
		price: 65.00,
		category: 'Sports',
		imageUrl: 'https://picsum.photos/seed/prod8/400/300',
	},
	{
		id: 'prod9',
		name: 'Wireless Charging Pad',
		description:
			'Fast wireless charging pad compatible with all Qi-enabled devices.',
		price: 39.99,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod9/400/300',
	},
	{
		id: 'prod10',
		name: 'Gourmet Chocolate Box',
		description:
			'Handcrafted assorted chocolates made with premium Belgian cocoa.',
		price: 42.50,
		category: 'Groceries',
		imageUrl: 'https://picsum.photos/seed/prod10/400/300',
	},
	{
		id: 'prod11',
		name: 'Ceramic Coffee Mug Set',
		description:
			'Set of 4 handmade ceramic mugs perfect for your morning coffee ritual.',
		price: 55.00,
		category: 'Home & Kitchen',
		imageUrl: 'https://picsum.photos/seed/prod11/400/300',
	},
	{
		id: 'prod12',
		name: 'LED Desk Lamp',
		description:
			'Adjustable LED desk lamp with multiple brightness levels and color temperatures.',
		price: 79.99,
		category: 'Home & Kitchen',
		imageUrl: 'https://picsum.photos/seed/prod12/400/300',
	},
	{
		id: 'prod13',
		name: 'Merino Wool Scarf',
		description:
			'Luxurious and warm merino wool scarf available in multiple colors.',
		price: 68.00,
		category: 'Apparel',
		imageUrl: 'https://picsum.photos/seed/prod13/400/300',
	},
	{
		id: 'prod14',
		name: 'Portable Bluetooth Speaker',
		description:
			'Compact waterproof speaker with 12-hour battery life and crystal clear sound.',
		price: 125.99,
		category: 'Electronics',
		imageUrl: 'https://picsum.photos/seed/prod14/400/300',
	},
	{
		id: 'prod15',
		name: 'Essential Oils Gift Set',
		description:
			'Collection of 6 pure essential oils for aromatherapy and relaxation.',
		price: 89.95,
		category: 'Health & Beauty',
		imageUrl: 'https://picsum.photos/seed/prod15/400/300',
	},
]

export const CONTACTS_DATA: Contact[] = [
	{
		id: 'cont1',
		name: 'Ahmad Zulkifli',
		email: 'ahmad.zulkifli@example.my',
		phone: '012-3456789',
		address: {
			address_line1: 'No. 25, Jalan Kenanga',
			address_line2: 'Taman Sri Sentosa',
			address_line3: '',
			address_line4: '',
			city: 'Kuala Lumpur',
			state: 'Wilayah Persekutuan',
			postcode: '58000',
			country: 'Malaysia',
		},
		company: 'ZulTech Solutions',
	},
	{
		id: 'cont2',
		name: 'Hafiz Rahman',
		email: 'hafiz.rahman@example.my',
		phone: '012-1122334',
		address: {
			address_line1: 'No. 10, Jalan Persiaran Perdana',
			address_line2: 'Residensi Putrajaya, Blok B',
			address_line3: 'Presint 15',
			address_line4: 'Putrajaya',
			city: 'Putrajaya',
			state: 'Wilayah Persekutuan',
			postcode: '62050',
			country: 'Malaysia',
		},
		company: 'Putrajaya SmartTech',
	},
	{
		id: 'cont3',
		name: 'Lim Wei Sheng',
		email: 'lim.wei.sheng@example.my',
		phone: '016-2233445',
		address: {
			address_line1: '23, Jalan Impian Perdana',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Johor Bahru',
			state: 'Johor',
			postcode: '81200',
			country: 'Malaysia',
		},
		company: 'Southern IT Hub',
	},
	{
		id: 'cont4',
		name: 'Siti Mariam Abdullah',
		email: 'siti.mariam@example.my',
		phone: '013-9988776',
		address: {
			address_line1: 'Block C, Tingkat 5, Pangsapuri Aman',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Kota Bharu',
			state: 'Kelantan',
			postcode: '15050',
			country: 'Malaysia',
		},
		company: 'Kelantan Digital Works',
	},
	{
		id: 'cont5',
		name: 'Chong Mei Lin',
		email: 'mei.lin.chong@example.my',
		phone: '013-3344556',
		address: {
			address_line1: 'Unit 12-5, Kondominium Tropika',
			address_line2: 'Jalan Bukit Indah 3/2',
			address_line3: 'Taman Bukit Indah',
			address_line4: 'Iskandar Puteri',
			city: 'Johor Bahru',
			state: 'Johor',
			postcode: '79100',
			country: 'Malaysia',
		},
		company: 'Southern Vista Holdings',
	},
	{
		id: 'cont6',
		name: 'Tan Siew Ling',
		email: 'siew.ling.tan@example.my',
		phone: '019-4455667',
		address: {
			address_line1: '12, Jalan Tun Razak',
			address_line2: 'Tingkat 3, Menara Damai',
			address_line3: '',
			address_line4: '',
			city: 'George Town',
			state: 'Pulau Pinang',
			postcode: '10400',
			country: 'Malaysia',
		},
		company: 'Penang Techno Hub',
	},
	{
		id: 'cont7',
		name: 'Mohd Faizal Bin Ali',
		email: 'faizal.ali@example.my',
		phone: '010-7766554',
		address: {
			address_line1: 'No. 3, Jalan Indah Jaya 1',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Kuantan',
			state: 'Pahang',
			postcode: '25200',
			country: 'Malaysia',
		},
		company: 'East Coast Ventures',
	},
	{
		id: 'cont8',
		name: 'Amira Zainal',
		email: 'amira.zainal@example.my',
		phone: '014-8899001',
		address: {
			address_line1: 'Pusat Komersial Desa Ilmu',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Kota Samarahan',
			state: 'Sarawak',
			postcode: '94300',
			country: 'Malaysia',
		},
		company: 'Borneo Creative Co.',
	},
	{
		id: 'cont9',
		name: 'Zarina Abdul Latif',
		email: 'zarina.latif@example.my',
		phone: '019-5566778',
		address: {
			address_line1: 'Bangunan A, Tingkat 6',
			address_line2: 'Kompleks Perniagaan Teratai',
			address_line3: 'Jalan Tun Ahmad Zaidi',
			address_line4: 'Kuching',
			city: 'Kuching',
			state: 'Sarawak',
			postcode: '93150',
			country: 'Malaysia',
		},
		company: 'Sarawak Business Systems',
	},
	{
		id: 'cont10',
		name: 'Farah Izzati',
		email: 'farah.izzati@example.my',
		phone: '015-6677889',
		address: {
			address_line1: 'No. 7, Jalan Wawasan',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Seremban',
			state: 'Negeri Sembilan',
			postcode: '70300',
			country: 'Malaysia',
		},
		company: 'Visionary Solutions MY',
	},
	{
		id: 'cont11',
		name: 'Rohana Mohd Noor',
		email: 'rohana.noor@example.my',
		phone: '017-6655443',
		address: {
		  address_line1: 'No. 8, Jalan Air Itam',
		  address_line2: 'Taman Desa Ria',
		  address_line3: 'Pulau Pinang',
		  address_line4: '',
		  city: 'George Town',
		  state: 'Pulau Pinang',
		  postcode: '11500',
		  country: 'Malaysia',
		},
		company: 'Northern Impact Services',
	  }
]

