import type { Contact, Product } from '../types'

export const PRODUCTS_DATA: Product[] = [
	{
		id: 'box1',
		name: 'Custom Mailer Boxes',
		description:
			'Durable and fully customizable mailer boxes for e-commerce packaging. Great for shipping and branding.',
		price: 2.50,
		category: 'Packaging Boxes',
		imageUrl: 'https://picsum.photos/seed/box1/400/300',
	},
	{
		id: 'box2',
		name: 'Printed Corrugated Shipping Boxes',
		description:
			'Strong corrugated boxes printed with your logo or design. Perfect for heavier items.',
		price: 3.25,
		category: 'Shipping Boxes',
		imageUrl: 'https://picsum.photos/seed/box2/400/300',
	},
	{
		id: 'box3',
		name: 'Custom Product Boxes',
		description:
			'High-quality boxes ideal for cosmetics, supplements, and retail items. Glossy or matte finishes available.',
		price: 1.80,
		category: 'Retail Packaging',
		imageUrl: 'https://picsum.photos/seed/box3/400/300',
	},
	{
		id: 'box4',
		name: 'Custom Cake & Bakery Boxes',
		description:
			'Food-safe printed boxes for cakes, pastries, and other bakery items. Various sizes available.',
		price: 1.20,
		category: 'Food Packaging',
		imageUrl: 'https://picsum.photos/seed/box4/400/300',
	},
	{
		id: 'box5',
		name: 'Custom Gift Boxes',
		description:
			'Luxury gift boxes with custom printing, ideal for special occasions and product packaging.',
		price: 3.90,
		category: 'Gift Packaging',
		imageUrl: 'https://picsum.photos/seed/box5/400/300',
	},
	{
		id: 'box6',
		name: 'Custom Kraft Boxes',
		description:
			'Eco-friendly kraft boxes with minimalist designs. Ideal for organic or handmade products.',
		price: 1.60,
		category: 'Eco Packaging',
		imageUrl: 'https://picsum.photos/seed/box6/400/300',
	},
	{
		id: 'box7',
		name: 'Custom Takeaway Food Boxes',
		description:
			'Leak-proof, sturdy takeaway food boxes with full-color printing. Suitable for F&B businesses.',
		price: 0.95,
		category: 'Food Packaging',
		imageUrl: 'https://picsum.photos/seed/box7/400/300',
	},
	{
		id: 'box8',
		name: 'Custom Candle Boxes',
		description:
			'Stylish candle packaging with inserts and window cut-outs. Perfect for retail and gifting.',
		price: 2.10,
		category: 'Retail Packaging',
		imageUrl: 'https://picsum.photos/seed/box8/400/300',
	},
	{
		id: 'box9',
		name: 'Custom Display Boxes',
		description:
			'Printed display boxes for point-of-sale counters. Great for showcasing small products.',
		price: 1.75,
		category: 'Display Packaging',
		imageUrl: 'https://picsum.photos/seed/box9/400/300',
	},
	{
		id: 'box10',
		name: 'Custom Apparel Boxes',
		description:
			'Flat or rigid boxes designed for clothing brands. Add custom inserts and thank-you cards.',
		price: 2.85,
		category: 'Apparel Packaging',
		imageUrl: 'https://picsum.photos/seed/box10/400/300',
	},
	{
		id: 'box11',
		name: 'Custom Magnetic Closure Boxes',
		description:
			'Premium boxes with magnetic flaps and custom foam inserts. Ideal for luxury products.',
		price: 5.90,
		category: 'Luxury Packaging',
		imageUrl: 'https://picsum.photos/seed/box11/400/300',
	},
	{
		id: 'box12',
		name: 'Custom Pizza Boxes',
		description:
			'Food-grade pizza boxes with your restaurant branding. Grease-resistant and recyclable.',
		price: 1.05,
		category: 'Food Packaging',
		imageUrl: 'https://picsum.photos/seed/box12/400/300',
	},
	{
		id: 'box13',
		name: 'Custom Sleeve Boxes',
		description:
			'Sleek box with sliding sleeve – perfect for electronics, accessories, and gifts.',
		price: 2.40,
		category: 'Retail Packaging',
		imageUrl: 'https://picsum.photos/seed/box13/400/300',
	},
	{
		id: 'box14',
		name: 'Custom Soap Boxes',
		description:
			'Compact boxes designed for handmade soap and skincare products. Window or cut-out options available.',
		price: 0.85,
		category: 'Personal Care Packaging',
		imageUrl: 'https://picsum.photos/seed/box14/400/300',
	},
	{
		id: 'box15',
		name: 'Custom Box Design Service',
		description:
			'Don’t have a design? Our team will create professional, print-ready artwork for your custom boxes.',
		price: 49.00,
		category: 'Design Service',
		imageUrl: 'https://picsum.photos/seed/box15/400/300',
	},
];

export const CONTACTS_DATA: Contact[] = [
	{
		id: 'cont1',
		name: 'Ahmad Zulkifli',
		email: 'ahmad.zulkifli@example.my',
		phone: '012-3456789',
		address: {
			address_line1: 'No. 25, Jalan Kenanga',
			address_line2: 'Taman Sri Sentosa',
			address_line3: '',
			address_line4: '',
			city: 'Kuala Lumpur',
			state: 'Wilayah Persekutuan',
			postcode: '58000',
			country: 'Malaysia',
		},
		company: 'ZulTech Solutions',
	},
	{
		id: 'cont2',
		name: 'Hafiz Rahman',
		email: 'hafiz.rahman@example.my',
		phone: '012-1122334',
		address: {
			address_line1: 'No. 10, Jalan Persiaran Perdana',
			address_line2: 'Residensi Putrajaya, Blok B',
			address_line3: 'Presint 15',
			address_line4: 'Putrajaya',
			city: 'Putrajaya',
			state: 'Wilayah Persekutuan',
			postcode: '62050',
			country: 'Malaysia',
		},
		company: 'Putrajaya SmartTech',
	},
	{
		id: 'cont3',
		name: 'Lim Wei Sheng',
		email: 'lim.wei.sheng@example.my',
		phone: '016-2233445',
		address: {
			address_line1: '23, Jalan Impian Perdana',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Johor Bahru',
			state: 'Johor',
			postcode: '81200',
			country: 'Malaysia',
		},
		company: 'Southern IT Hub',
	},
	{
		id: 'cont4',
		name: 'Siti Mariam Abdullah',
		email: 'siti.mariam@example.my',
		phone: '013-9988776',
		address: {
			address_line1: 'Block C, Tingkat 5, Pangsapuri Aman',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Kota Bharu',
			state: 'Kelantan',
			postcode: '15050',
			country: 'Malaysia',
		},
		company: 'Kelantan Digital Works',
	},
	{
		id: 'cont5',
		name: 'Chong Mei Lin',
		email: 'mei.lin.chong@example.my',
		phone: '013-3344556',
		address: {
			address_line1: 'Unit 12-5, Kondominium Tropika',
			address_line2: 'Jalan Bukit Indah 3/2',
			address_line3: 'Taman Bukit Indah',
			address_line4: 'Iskandar Puteri',
			city: 'Johor Bahru',
			state: 'Johor',
			postcode: '79100',
			country: 'Malaysia',
		},
		company: 'Southern Vista Holdings',
	},
	{
		id: 'cont6',
		name: 'Tan Siew Ling',
		email: 'siew.ling.tan@example.my',
		phone: '019-4455667',
		address: {
			address_line1: '12, Jalan Tun Razak',
			address_line2: 'Tingkat 3, Menara Damai',
			address_line3: '',
			address_line4: '',
			city: 'George Town',
			state: 'Pulau Pinang',
			postcode: '10400',
			country: 'Malaysia',
		},
		company: 'Penang Techno Hub',
	},
	{
		id: 'cont7',
		name: 'Mohd Faizal Bin Ali',
		email: 'faizal.ali@example.my',
		phone: '010-7766554',
		address: {
			address_line1: 'No. 3, Jalan Indah Jaya 1',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Kuantan',
			state: 'Pahang',
			postcode: '25200',
			country: 'Malaysia',
		},
		company: 'East Coast Ventures',
	},
	{
		id: 'cont8',
		name: 'Amira Zainal',
		email: 'amira.zainal@example.my',
		phone: '014-8899001',
		address: {
			address_line1: 'Pusat Komersial Desa Ilmu',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Kota Samarahan',
			state: 'Sarawak',
			postcode: '94300',
			country: 'Malaysia',
		},
		company: 'Borneo Creative Co.',
	},
	{
		id: 'cont9',
		name: 'Zarina Abdul Latif',
		email: 'zarina.latif@example.my',
		phone: '019-5566778',
		address: {
			address_line1: 'Bangunan A, Tingkat 6',
			address_line2: 'Kompleks Perniagaan Teratai',
			address_line3: 'Jalan Tun Ahmad Zaidi',
			address_line4: 'Kuching',
			city: 'Kuching',
			state: 'Sarawak',
			postcode: '93150',
			country: 'Malaysia',
		},
		company: 'Sarawak Business Systems',
	},
	{
		id: 'cont10',
		name: 'Farah Izzati',
		email: 'farah.izzati@example.my',
		phone: '015-6677889',
		address: {
			address_line1: 'No. 7, Jalan Wawasan',
			address_line2: '',
			address_line3: '',
			address_line4: '',
			city: 'Seremban',
			state: 'Negeri Sembilan',
			postcode: '70300',
			country: 'Malaysia',
		},
		company: 'Visionary Solutions MY',
	},
	{
		id: 'cont11',
		name: 'Rohana Mohd Noor',
		email: 'rohana.noor@example.my',
		phone: '017-6655443',
		address: {
			address_line1: 'No. 8, Jalan Air Itam',
			address_line2: 'Taman Desa Ria',
			address_line3: 'Pulau Pinang',
			address_line4: '',
			city: 'George Town',
			state: 'Pulau Pinang',
			postcode: '11500',
			country: 'Malaysia',
		},
		company: 'Northern Impact Services',
	}
]

